version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn spring-boot:build-image
  post_build:
    commands:
    - echo Build completed on `date`
    - mv target/cs203-project-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - cs203-project-0.0.1-SNAPSHOT.jar
  # - .ebextensions/**/*