server:
  port: 8080

# These values for Cognito are meant to be public
# They are not sensitive.
com:
  kb:
    jwt:
      aws:
        userPoolId: "ap-southeast-1_jVulnk9is"
        region: "ap-southeast-1"